name: MyWorkFlow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-slim

    steps:
      - name: first-stage
        run: echo "welcome to First Github Pipeline"

      - name: second-stage
        run: echo "this is my second stage"
