name: mypipeline

on:
  workflow_dispatch:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4


      - name: docker
        run: |
          docker build -t image1 .

      - name: deploy
        run: docker run -itd --name cont1 -p 1234:80 image1
